server:
  address:
    0.0.0.0
  port: 8081
#数据库配置
spring:
    servlet:
      multipart:
        enabled: true
        maxFileSize: 10MB
        maxRequestSize: 100MB
    mvc:
       throw-exception-if-no-handler-found: true
    resources:
      add-mappings:false 
    application : 
       name : youguo-server
    datasource:
        url: jdbc:mysql://39.105.153.98:3306/scss?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
        username: root
        password: YoGoYun.com
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

 
   
   
      
mybatis:
  type-aliases-package: com.yogo.dao
  mapper-locations: classpath:mapper/*.xml
  #configLocation: classpath:mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#pagehelper
pagehelper: 
   helperDialect : mysql
   reasonable: true
   support-methods-arguments: true
   params: count=countSql




